Rscript myJob.R --impute=MeanMode --filter=pca --model=BARTModel
Rscript myJob.R --impute=knn --filter=pca --model=BARTModel
Rscript myJob.R --impute=bag --filter=pca --model=BARTModel
Rscript myJob.R --impute=MeanMode --filter=corr --model=BARTModel
Rscript myJob.R --impute=knn --filter=corr --model=BARTModel
Rscript myJob.R --impute=bag --filter=corr --model=BARTModel
Rscript myJob.R --impute=MeanMode --filter=none --model=BARTModel
Rscript myJob.R --impute=knn --filter=none --model=BARTModel
Rscript myJob.R --impute=bag --filter=none --model=BARTModel
Rscript myJob.R --impute=MeanMode --filter=pca --model=SVMRad
Rscript myJob.R --impute=knn --filter=pca --model=SVMRad
Rscript myJob.R --impute=bag --filter=pca --model=SVMRad
Rscript myJob.R --impute=MeanMode --filter=corr --model=SVMRad
Rscript myJob.R --impute=knn --filter=corr --model=SVMRad
Rscript myJob.R --impute=bag --filter=corr --model=SVMRad
Rscript myJob.R --impute=MeanMode --filter=none --model=SVMRad
Rscript myJob.R --impute=knn --filter=none --model=SVMRad
Rscript myJob.R --impute=bag --filter=none --model=SVMRad
Rscript myJob.R --impute=MeanMode --filter=pca --model=NNet
Rscript myJob.R --impute=knn --filter=pca --model=NNet
Rscript myJob.R --impute=bag --filter=pca --model=NNet
Rscript myJob.R --impute=MeanMode --filter=corr --model=NNet
Rscript myJob.R --impute=knn --filter=corr --model=NNet
Rscript myJob.R --impute=bag --filter=corr --model=NNet
Rscript myJob.R --impute=MeanMode --filter=none --model=NNet
Rscript myJob.R --impute=knn --filter=none --model=NNet
Rscript myJob.R --impute=bag --filter=none --model=NNet
Rscript myJob.R --impute=MeanMode --filter=pca --model=GLM
Rscript myJob.R --impute=knn --filter=pca --model=GLM
Rscript myJob.R --impute=bag --filter=pca --model=GLM
Rscript myJob.R --impute=MeanMode --filter=corr --model=GLM
Rscript myJob.R --impute=knn --filter=corr --model=GLM
Rscript myJob.R --impute=bag --filter=corr --model=GLM
Rscript myJob.R --impute=MeanMode --filter=none --model=GLM
Rscript myJob.R --impute=knn --filter=none --model=GLM
Rscript myJob.R --impute=bag --filter=none --model=GLM
